### ISSUE TITLE
Help on RegMon output

### ISSUE THREAD

**Issue by inamiitb** [thuehn/RegMon#12]
I have installed RegMon on LEDE on a MikroTik board (rb433). But how do I get the RegMon graphs on the Luci web interface? Right now, the RegMon graph page of Luci is like this:
![screenshot from 2017-11-10 23-24-48](https://user-images.githubusercontent.com/24293667/32671990-8304758e-c66f-11e7-8982-f79adccf1144.png)

and the Regmon config page is:
![screenshot from 2017-11-10 23-25-28](https://user-images.githubusercontent.com/24293667/32672028-a239427c-c66f-11e7-84d1-4e31143fa4b1.png)

![screenshot from 2017-11-10 23-25-51](https://user-images.githubusercontent.com/24293667/32672030-a266465a-c66f-11e7-867b-062a4cf2cda9.png)

ANy help is appreciated
Regards
Inam

**Comment by inamiitb** [comment]
Can anybody tell what is the minimum settings I need to set to get the default graphs in Regmon interface, as shown here:
https://github.com/thuehn/RegMon#example-of-regmons-luci-web-interface-view
Regards
Inam

**Comment by thuehn** [comment]
Hi Inam,

From the web interface view you provided, I looks like you have successfully installed the luci-app but the regmon patches that need to be applayed to ath9k in order to get the regmon statistics are not applied. How did you applied the necessary regmon patches to your lede environment ?
Greetings Thomas

**Comment by thuehn** [comment]
Assumed you have an Atheros ath9k based WiFi card in your router you need 2 RegMon patches copied into your LEDE /mac80211 environment in order to get RegMon working.
Just copy those two patches: 9982-ath9k_RegMon.patch & 9983-ath9k_prevent_cycle_count.. from the RegMon/src folder into your /lede/package/kernel/mac80211/patches folder. Than recompile your image and flash it (a "make package/mac80211/clean && make" ensures you apply those new patches in the new image).
To validate that RegMon is working on your router, you should see measurement data printed out by issuing a "cat /sys/kernel/debug/ieee80211/phy0/regmon/register_log" .. if this is an empty file, you the patches does not got applied properly in the image or you do not have a ath9k based WiFi card.

Greetings Thomas

**Comment by inamiitb** [comment]
Thank you Thomas for answering. 
Incidentally, after flashing LEDE, I came to know that I had to manually enable wireless, which is otherwise disabled by default. And that made RegMon work. 
I was wondering I had followed all your instructions (superbly written), then why it didn't work?
Thanks and regards.
Inam

**Comment by thuehn** [comment]
cool ... so you got it working at your side.

Than happy wifi monitoring & measurements of the mac activities.

GReetings from Berlin
Thomas
